//go:build ignore

package controllers
package controllers

import (

































































































































}	}		t.Fatalf("expected invalid file type message, got: %s", w.Body.String())	if !bytes.Contains(w.Body.Bytes(), []byte("invalid file type")) {	}		t.Fatalf("expected no forwarding to image service for invalid content type")	if forwarded {	}		t.Fatalf("expected 400, got %d, body: %s", w.Code, w.Body.String())	if w.Code != http.StatusBadRequest {	r.ServeHTTP(w, req)	w := httptest.NewRecorder()	req := makeMultipartUploadRequest(t, "/upload", "image", "notes.txt", "text/plain", []byte("not-an-image"))	})		userPostMeImage(c)		c.Set("currentUser", user_pkg.User{ID: currentUserID})	r.POST("/upload", func(c *gin.Context) {	r := gin.New()	config.InternalImageService = imageService.URL	defer imageService.Close()	}))		w.WriteHeader(http.StatusOK)		forwarded = true	imageService := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {	forwarded := false	currentUserID := uuid.NewV4()	gin.SetMode(gin.TestMode)func TestUserPostMeImage_RejectsNonImageContentType(t *testing.T) {}	}		t.Fatalf("expected response worked=true, got: %v", payload)	if !ok || !worked {	worked, ok := payload["worked"].(bool)	}		t.Fatalf("expected json response, got error: %v", err)	if err := json.Unmarshal(w.Body.Bytes(), &payload); err != nil {	var payload map[string]any	}		t.Fatalf("expected forwarded path %s, got %s", expectedPath, forwardedPath)	if forwardedPath != expectedPath {	expectedPath := "/api/users/" + currentUserID.String()	}		t.Fatalf("expected request to be forwarded to image service")	if !forwarded {	}		t.Fatalf("expected 200, got %d, body: %s", w.Code, w.Body.String())	if w.Code != http.StatusOK {	r.ServeHTTP(w, req)	w := httptest.NewRecorder()	req := makeMultipartUploadRequest(t, "/upload", "image", "avatar.jpg", "image/jpeg", []byte("fake-jpeg-content"))	})		userPostMeImage(c)		c.Set("currentUser", user_pkg.User{ID: currentUserID})	r.POST("/upload", func(c *gin.Context) {	r := gin.New()	config.InternalImageService = imageService.URL	defer imageService.Close()	}))		w.WriteHeader(http.StatusOK)		forwardedPath = r.URL.Path		forwarded = true	imageService := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {	var forwardedPath string	forwarded := false	currentUserID := uuid.NewV4()	gin.SetMode(gin.TestMode)func TestUserPostMeImage_SuccessForwardsToImageService(t *testing.T) {}	return req	req.Header.Set("Content-Type", writer.FormDataContentType())	req := httptest.NewRequest(http.MethodPost, route, &body)	}		t.Fatalf("failed to close multipart writer: %v", err)	if err := writer.Close(); err != nil {	}		t.Fatalf("failed to write multipart content: %v", err)	if _, err := part.Write(content); err != nil {	}		t.Fatalf("failed to create multipart part: %v", err)	if err != nil {	part, err := writer.CreatePart(partHeader)	}		partHeader.Set("Content-Type", contentType)	if contentType != "" {	partHeader.Set("Content-Disposition", `form-data; name="`+fieldName+`"; filename="`+fileName+`"`)	partHeader := textproto.MIMEHeader{}	writer := multipart.NewWriter(&body)	var body bytes.Buffer	t.Helper()func makeMultipartUploadRequest(t *testing.T, route string, fieldName string, fileName string, contentType string, content []byte) *http.Request {)	uuid "github.com/satori/go.uuid"	"github.com/gin-gonic/gin"	user_pkg "github.com/fabiokaelin/f-oauth/pkg/user"	"github.com/fabiokaelin/f-oauth/config"	"testing"	"net/textproto"	"net/http/httptest"	"net/http"	"mime/multipart"	"encoding/json"	"bytes"