apiVersion: k8s.fabkli.ch/v1
kind: Fdeployment
metadata:
  name: oauth-frontend
spec:
  path: "/"
  replicas: 1
  port: 80
  tag: "latest"
  resources:
    limits:
      cpu: 200m
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 128Mi
  healthCheck:
    livenessProbe:
      path: "/"
    readinessProbe:
      path: "/"
  host: "oauth.fabkli.ch"
  env:
    - name: VITE_SERVER_ENDPOINT
      value: https://oauth.fabkli.ch
    - name: VITE_GOOGLE_OAUTH_CLIENT_ID
      value: 755737563752-u021il7839sit5gt4k11ag3poa9opu84.apps.googleusercontent.com
    - name: VITE_GOOGLE_OAUTH_REDIRECT
      value: https://oauth.fabkli.ch/api/sessions/oauth/google
    - name: VITE_GITHUB_OAUTH_REDIRECT_URL
      value: https://oauth.fabkli.ch/api/sessions/oauth/github