apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db
  namespace: oauth
  labels:
    app: db
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: oauth
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None
---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: dev-db-config
#   namespace: oauth
# data:
#   MARIADB_DATABASE: oauth
#   MARIADB_ROOT_HOST: "localhost"
#   MARIADB_USER: oauthuser
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
  namespace: oauth
data:
  custom.cnf: |
    [mysqld]
    innodb_buffer_pool_size=64M
    innodb_log_buffer_size=8M
    query_cache_size=16M
#    max_connections=50
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: oauth
spec:
  serviceName: "db"
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: mariadb
          image: mariadb:11
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_DATABASE
              value: oauth
              # valueFrom:
              #   configMapKeyRef:
              #     name: dev-db-config
              #     key: MARIADB_DATABASE
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oauth-secrets
                  key: DATABASE_ROOT_PASSWORD
            - name: MARIADB_ROOT_HOST
              value: "localhost"
              # valueFrom:
              #   configMapKeyRef:
              #     name: dev-db-config
              #     key: MARIADB_ROOT_HOST
            - name: MARIADB_USER
              value: oauthuser
              # valueFrom:
              #   configMapKeyRef:
              #     name: dev-db-config
              #     key: MARIADB_USER
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oauth-secrets
                  key: DATABASE_PASSWORD
          resources:
            requests:
              memory: "128Mi"
              cpu: "5m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
          volumeMounts:
            - name: db-pv
              mountPath: /var/lib/mysql
              readOnly: false
            - name: mariadb-config
              mountPath: /etc/mysql/conf.d
              readOnly: true
      volumes:
        - name: db-pv
          persistentVolumeClaim:
            claimName: db
        - name: mariadb-config
          configMap:
            name: mariadb-config

      tolerations:
        - effect: NoSchedule
          key: kubernetes.azure.com/scalesetpriority
          operator: Equal
          value: spot
      securityContext:
        runAsNonRoot: true
        fsGroup: 2000
        runAsUser: 1001
        runAsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
